###########
# site.title

title:    'Sirius-3'
subtitle: 'DQN-Based AI Agent for Adaptive Threat Detection and Defense (in Minecraft)'


#########################
# more settings

markdown: kramdown

exclude:
- README.md
- LICENSE.md
